<a href="https://colab.research.google.com/github/ummmars/Integrated-Notification-Service-PHP/blob/main/DataScienceLab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df = pd.read_csv('./CoffeeAndCode.csv', na_values=["n/a", "NaN", "", " "])
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CodingHours          100 non-null    int64
 1   CoffeeCupsPerDay     100 non-null    int64
 2   CoffeeTime           100 non-null    object
 3   CodingWithoutCoffee  100 non-null    object
 4   CoffeeType           99 non-null     object
 5   CoffeeSolveBugs      98 non-null     object
 6   Gender               96 non-null     object
 7   Country              100 non-null    object
 8   AgeRange             98 non-null     object
dtypes: int64(2), object(7)
memory usage: 7.2+ KB

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
0,8,2,Before coding,Yes,Caffè latte,Sometimes,Female,Lebanon,18 to 29
1,3,2,Before coding,Yes,Americano,Yes,Female,Lebanon,30 to 39
2,5,3,While coding,No,Nescafe,Yes,Female,Lebanon,18 to 29
3,8,2,Before coding,No,Nescafe,Yes,Male,Lebanon,NaN
4,10,3,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29

In [6]:
null_masks = df.isnull().any(axis=1)
null_masks

0     False
1     False
2     False
3      True
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [7]:
null_masks = df.isnull().any(axis=1)
null_data = df[null_masks]
null_data

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
3,8,2,Before coding,No,Nescafe,Yes,Male,Lebanon,NaN
6,5,2,While coding,Yes,Nescafe,Sometimes,Male,Lebanon,NaN
13,9,3,While coding,Sometimes,Nescafe,NaN,Male,Lebanon,30 to 39
18,8,3,While coding,No,Nescafe,No,NaN,Lebanon,18 to 29
26,7,4,Before coding,Sometimes,Espresso (Short Black),No,NaN,Lebanon,30 to 39
31,2,2,While coding,No,Nescafe,Sometimes,NaN,Lebanon,18 to 29
40,8,2,While coding,Sometimes,Turkish,No,NaN,Lebanon,30 to 39
43,10,6,While coding,Sometimes,NaN,No,Male,Lebanon,18 to 29
75,6,6,While coding,Sometimes,Cappuccino,NaN,Male,Lebanon,18 to 29

In [8]:
for column in df:
  print(column,": ")
  print(df[column].unique(), "\n")

CodingHours :
[ 8  3  5 10  2  9  6  4  7  1]

CoffeeCupsPerDay :
[2 3 4 1 5 6 7 8]

CoffeeTime :
['Before coding' 'While coding' 'Before and while coding' 'In the morning'
 'All the time' 'After coding' 'No specific time']

CodingWithoutCoffee :
['Yes' 'No' 'Sometimes' 'Sometim' '30']

CoffeeType :
['Caffè latte' 'Americano' 'Nescafe' 'Turkish' 'American Coffee'
 'Espresso (Short Black)' 'Cappuccino' '70' nan 'Double Espresso (Doppio)'
 '-200']

CoffeeSolveBugs :
['Sometimes' 'Yes' 'No' nan '-200' 'yeap' 'N' 'Not' 'Yeap']

Gender :
['Female' 'Male' 'Lady' nan 'm']

Country :
['Lebanon']

AgeRange :
['18 to 29' '30 to 39' nan '40 to 49' 'Under 18' '50 to 59']

In [9]:
import numpy as np
cell = np.nan

In [10]:
df['CodingWithoutCoffee'][df['CodingWithoutCoffee']=="Sometim"]

16    Sometim
89    Sometim
Name: CodingWithoutCoffee, dtype: object

In [19]:
import numpy as np
df['CodingWithoutCoffee'][df['CodingWithoutCoffee']=="Sometim"]="Sometimes"
df['CodingWithoutCoffee'].unique()

/tmp/ipykernel_756/2123577532.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['CodingWithoutCoffee'][df['CodingWithoutCoffee']=="Sometim"]="Sometimes"
/tmp/ipykernel_756/2123577532.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CodingWithoutCoffee'][df['CodingWithoutCoffee']=="Sometim"]="Sometimes"

array(['Yes', 'No', 'Sometimes', '30'], dtype=object)

In [21]:
import numpy as np
df['CodingWithoutCoffee'][df['CodingWithoutCoffee']=="30"]=np.nan
df['CodingWithoutCoffee'].unique()

/tmp/ipykernel_756/4233848468.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['CodingWithoutCoffee'][df['CodingWithoutCoffee']=="30"]=np.nan
/tmp/ipykernel_756/4233848468.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CodingWithoutCoffee'][df['CodingWithoutCoffee']=="30"]=np.nan

array(['Yes', 'No', 'Sometimes', nan], dtype=object)

In [24]:
for column in df:
  print(column,": ")
  print(df[column].unique(), "\n")

CodingHours :
[ 8  3  5 10  2  9  6  4  7  1]

CoffeeCupsPerDay :
[2 3 4 1 5 6 7 8]

CoffeeTime :
['Before coding' 'While coding' 'Before and while coding' 'In the morning'
 'All the time' 'After coding' 'No specific time']

CodingWithoutCoffee :
['Yes' 'No' 'Sometimes' nan]

CoffeeType :
['Caffè latte' 'Americano' 'Nescafe' 'Turkish' 'American Coffee'
 'Espresso (Short Black)' 'Cappuccino' '70' nan 'Double Espresso (Doppio)'
 '-200']

CoffeeSolveBugs :
['Sometimes' 'Yes' 'No' nan '-200' 'yeap' 'N' 'Not' 'Yeap']

Gender :
['Female' 'Male' 'Lady' nan 'm']

Country :
['Lebanon']

AgeRange :
['18 to 29' '30 to 39' nan '40 to 49' 'Under 18' '50 to 59']

In [23]:
df['CodingWithoutCoffee'].unique()

array(['Yes', 'No', 'Sometimes', nan], dtype=object)